services:
  circle-game:
    container_name: perfect-circle-game
    image: sharfy9/perfect-circle-game:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8687:80"
    restart: unless-stopped